-- Add new columns to novtra_products table
ALTER TABLE public.novtra_products
ADD COLUMN IF NOT EXISTS is_winner BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS thumbnail_url TEXT,
ADD COLUMN IF NOT EXISTS roas TEXT,
ADD COLUMN IF NOT EXISTS total_profit NUMERIC,
ADD COLUMN IF NOT EXISTS avg_cpc TEXT,
ADD COLUMN IF NOT EXISTS eu_reach TEXT,
ADD COLUMN IF NOT EXISTS ad_type TEXT,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
